/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import io.Logger;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void loggerTest() {
        Logger.log("String three", this.getClass());
        Logger.log("String four", this.getClass());
        Logger.write("String three", this.getClass());
        Logger.write("String four", this.getClass());
    }
}
